### ISSUE TITLE
First time user question!

### ISSUE THREAD

**Issue by user6116** [afriscic/BarcodeScanning.Native.Maui#38] opened 2024-03-12 04:50 UTC
Hello.  I just installed barcodescanning for the first time and I really like it so far.  I do have a few questions that I couldn't figure out from the documentation.  If you could help guide me how to use this, that would be super helpful!  Here is my xaml code
`<scanner:CameraView x:Name="BarcodeView" 
                        HorizontalOptions="Fill" VerticalOptions="Fill" 
                        OnDetectionFinished="BarcodeView_OnDetectionFinished" 
                        BarcodeSymbologies="Upca" TapToFocusEnabled="True" 
                        VibrationOnDetected="True" />`

1) Give the above code, I was expecting the BarcodeView_OnDetectionFinished event to get fired only when a barcode was scanned.  It is being fired non stop with nothing in the e.BarcodeResults.  Is this normal behavior?
2) I specify BarcodeSymbologies="Upca", but the e.BarcodeResults is reading 2D barcodes on my iphone as well in the BarcodeView_OnDetectionFinished event.  How do I filter out just the Upca symbology?
3) I searched on the internet and couldn't figure out what "PoolingInterval" was.  What does that functionality do?

Thanks again and sorry for so many questions!

**Comment by afriscic** [comment] 2024-03-12 07:36
Hello.

1.  Yes, this is by design. It fires after every processed frame. You can do a simple `if (e.BarcodeResults > 0)` check to see if any barcodes are detected.
2. This is a bug, thanks for pointing it out. It happens only for "Upca" as it isn't explicitly defined in iOS Vision specification so I forgot to assign it. I'll fix this in new release. Other symbologies should be filtered as expected.
3. If you set PoolingInterval it will combine results from multiple frames and fire OnDetectionFinished event once after set amount of time in ms. Typical use case would be if you want to notify the user or go to another page as soon as some barcode is detected but you want to assure that all barcodes in cameras filed of view are detected, as it can happen that not all barcodes are detected in a frame at the same time.

**Comment by user6116** [comment] 2024-03-12 14:11
Oh, okay, all that makes sense.  It's weird that they don't have an symbiology for Upca.  [https://developer.apple.com/documentation/vision/vnbarcodesymbology](url).  From what I am reading with iOS you need to use EAN-13 and remove the leading zero.  

Have you done any analysis on the battery usage for decoding barcodes every frame?  My initial thought is that detecting barcodes on every frame seems like a lot of extra processing.  I could be wrong though.  Is there a way to dial down the frequency of the detection (not the camera, just the detection)?

**Comment by afriscic** [comment] 2024-03-13 18:11
Fixed in 1.3.0

**Closed by afriscic** 2024-03-13 18:11 UTC
