### ISSUE TITLE
After some time, the camera stops scanning.

### ISSUE THREAD

**Issue by OpterJohan-Hallberg** [afriscic/BarcodeScanning.Native.Maui#18] opened 2024-01-10 13:47 UTC
After starting the camera, (10 - 60 seconds) it stops firing the DetectionFinished event until the page is closed and opened again. I have been unable to find a workaround.
No messages in output, but logcat shows this.

01-10 10:26:25.550   948  2095 E CamX    : [ERROR][STATS_AWB] camxcawbmain.cpp:1852: AddDebugData Invalid debugData, return

01-10 10:26:25.563   948  2098 E CamX    : [ERROR][STATS_AWB] camxcawbmain.cpp:1329: AWBGetParameter  GetParam depth vendor Tag Start

01-10 10:26:25.563   948  2098 E CamX    : [ERROR][STATS_AWB] camxcawbmain.cpp:1391: AWBGetParameter  GetParam depth vendor Tag End, Tag Count : 0

01-10 10:26:25.591  1214  2732 I EDMNativeHelperService: isCameraEnabled

01-10 10:26:25.593  1214  2732 D EDMNativeHelper: isCameraEnabled

01-10 10:26:25.594  1214  2732 D EDMNativeHelper: checking for camera in EnterpriseDeviceManagerService

01-10 10:26:25.594  1214  2732 D EnterpriseDeviceManagerService: isCameraEnabledNative

01-10 10:26:25.594  1214  2732 D EnterpriseDeviceManagerService: checking for camera in restriction policy

01-10 10:26:25.594  1214  2732 D RestrictionPolicy: isCameraEnabled ret(true) userId(0) cxtInfo.mCallerUid(10761) cxtInfo.mContainerId(0)

01-10 10:26:25.609   948  2097 E CamX    : [ERROR][STATS_AWB] camxcawbmain.cpp:1852: AddDebugData Invalid debugData, return

01-10 10:26:25.633   948  2096 E CamX    : [ERROR][STATS_AWB] camxcawbmain.cpp:1329: AWBGetParameter  GetParam depth vendor Tag Start

01-10 10:26:25.634   948  2096 E CamX    : [ERROR][STATS_AWB] camxcawbmain.cpp:1391: AWBGetParameter GetParam depth vendor Tag End, Tag Count : 0

**Comment by OpterJohan-Hallberg** [comment] 2024-01-11 14:52
Did some more testing. I get an error on line 102 on BarcodeAnalyzer.cs on Android, when it stops scanning.

`{System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'AndroidX.Camera.Core.SettableImageProxy'.
   at Java.Interop.JniPeerMembers.AssertSelf(IJavaPeerable self) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.cs:line 153
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 57
   at AndroidX.Camera.Core.ForwardingImageProxy.Close()
   at BarcodeScanning.BarcodeAnalyzer.SafeCloseImageProxy(IImageProxy proxy) in C:\Users\Johan\source\repos\BarcodeScanning.Native.Maui\BarcodeScanning.Native.Maui\Platforms\Android\BarcodeAnalyzer.cs:line 102}`

**Comment by afriscic** [comment] 2024-01-18 08:32
HI.

I have encountered this exception before on other parts of this project but i can't reproduce it here. What android version do you use and which device? I have one low end and one a bit older hihg end device and I don't encounter it in either of them...
Try to upgrade Xamarin.AndroidX.Camera.Camera2 and Xamarin.AndroidX.Camera.View to 1.3.1 and see if it fixes it. I'll do it in next release.

**Comment by afriscic** [comment] 2024-01-18 12:17
For last 3 hours I'm trying to trigger this error but I'm unable to. Also I have an app in "production test" on Galaxy A12, Android 13 that runs for hours at a time and I'm not experiencing this error. There must be something different with our implementations...

Are you experiencing this when running the Test app from this project or in your app?
Have you maybe tried it in Release mode?
Can you catch this exception in catch block or is it thrown in the background?

Usually I encountered System.ObjectDisposedException when the camera is starting, stopping or view gets loaded, unloaded or disposed. That's why you see all this code in CameraViewHandler on various places:
` _ = Task.Run(async () =>
{
    await Task.Delay(_delay);
    MainThread.BeginInvokeOnMainThread(..);
});`

Problem here is that it is mandatory to close ImageProxy to get next frame from the camera to the analyzer. So if current ImageProxy that holds the current frame never gets closed, no new frames get delivered to the analyzer and nothing gets detected but camera looks OK.

Maybe try closing the image proxy through main thread like this:
`MainThread.BeginInvokeOnMainThread(() => proxy?.Close());`
of maybe add a delay before it:
`await Task.Delay(10);`
but I'm doubtful that it'll work... And the delay would slow down the process...

**Comment by afriscic** [comment] 2024-01-18 13:51
The only workaround i can think of is to invoke the Start method from CameraViewHandler instance (that you can pass through BarcodeAnalyzer constructor), with a delay and with BeginInvokeOnMainThread, from the catch block. That would restart the camera stream and analyzer instances. But camera preview would flicker so it wouldn't be the best user experience...

If I ever manage to reproduce the error I'll post here.

**Comment by OpterJohan-Hallberg** [comment] 2024-01-19 07:42
Running CameraViewHandler.Start from the catch seems to work, yes.

**Comment by afriscic** [comment] 2024-01-20 08:28
Thank you for the pull request. Can you please test one more think? Could you refactor the SafeCloseImageProxy like this:

private static void SafeCloseImageProxy(IImageProxy proxy, CameraViewHandler cameraViewHandler)
{
        try
        {
            proxy?.Close();
        }
        catch (Exception) 
        {
            MainThread.BeginInvokeOnMainThread(() => cameraViewHandler.Start());
        }
}

Based on your code i think this should work and it avoids the delay and all of async code.

**Comment by OpterJohan-Hallberg** [comment] 2024-01-20 09:32
Tested that and it still works fine, yeah. Updated pull request. Thanks!

**Comment by afriscic** [comment] 2024-01-24 17:28
Merged everything and did some minor code adjustments. Published in 1.2.4 release

**Closed by afriscic** 2024-01-24 17:28 UTC
