### ISSUE TITLE
I have a question. Please help me..

### ISSUE THREAD

**Issue by yunri91** [afriscic/BarcodeScanning.Native.Maui#24] opened 2024-01-24 00:27 UTC
Hello.
I am writing to you because I have a question.

The project is implementing a camera barcode scan,
I've tried to test the barcode scanning function, but no matter how many cameras I put on the barcode, the value is 0 or null in 'CameraView_OnDetectionFinished'.
What's the reason?

`<barcode:CameraView AbsoluteLayout.LayoutFlags="All"
                            AbsoluteLayout.LayoutBounds="0,0,1,1"
                            OnDetectionFinished="CameraView_OnDetectionFinished"
                            CaptureQuality="High"
                            ForceInverted="False"
                            TapToFocusEnabled="True"
                            BarcodeSymbologies="All"
                            CameraEnabled="True"

                            x:Name="Barcode"/>
private void CameraView_OnDetectionFinished(object sender, OnDetectionFinishedEventArg e)
{

    if (e.BarcodeResults.Count > 0)
    {
        //
    }

    
    var barcodeResults = e.BarcodeResults;
    if (barcodeResults.Count > 0)
    {

    }
    foreach (var result in e.BarcodeResults)
    {

    }
    _drawable.barcodeResults = e.BarcodeResults;
    Graphics.Invalidate();

}

Is the modal method the problem?
Above is the part that I call in my Main Page.

`
var barcodeScan = new BarcodeScan();
barcodeScan.OnValueScanned += (sender, value) =>
{
    if (value != null && value != "")
    {
        string valueFromPopup = value;

    }
   
};
await Navigation.PushModalAsync(barcodeScan);
`

**Comment by yunri91** [comment] 2024-01-24 05:54
@afriscic 
I'm sorry!
Fortunately, I checked that the scan value came in normally,
The CameraView_OnDetectionFinished method seems to have values coming in successively, so I think I just need to check that part!
Thank you for providing me with a good library!

**Comment by afriscic** [comment] 2024-01-24 07:47
Hello.

Sorry, I don't really understand your question but looks like you figured it out.
CameraView_OnDetectionFinished triggering is by design. OnDetectionFinished is called every time BarcodeAnalyzer finishes processing, if everything works well multiple times a second. This is to enable continuous feedback of the scanning process.

As everything seems OK I'll close the issue.

**Closed by afriscic** 2024-01-24 07:47 UTC
